config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.root                  :controller => 'dashboard'
  map.admin    '/admin',    :controller => 'admin/dashboard'
  map.login    '/login',    :controller => "user_sessions", :action => "new"
  map.logout   '/logout',   :controller => 'user_sessions', :action => 'destroy'
  map.register '/register', :controller => 'users',         :action => 'new'
  map.ajax     '/ajax/:action', :controller => 'ajax',      :action => 'update'
  map.form     '/form',     :controller => 'public',        :action => 'create'
  map.pdf '/pdf', :controller => 'dashboard', :action => 'generate_pdf'
  map.boletin '/boletin', :controller => 'api', :action => 'boletin'
  map.fail '/admin/error', :controller => 'admin/dashboard', :action => 'send_error'

  # PUBLIC
  map.resource  :user_session, :as => 'sesion'
  map.resource  :account, :controller => "users", :as => 'cuenta'
  map.resources :campaigns, :as => 'campanias', :collection => {:search => :get} do |campaign|
    campaign.resources :email_attachments, :as => 'adjuntos'
    campaign.resources :sendings, :as => 'envios', 
      :collection => {:test => :post}
    campaign.resources :sending_contacts, :as => 'contactos',
      :collection => {:search => :get}
  end
  map.resources :companies, :as => 'empresas', :collection => {:search => :get}
  map.resources :institution_types, :as => 'instituciones'
  map.resources :contacts, :as => 'contactos', :member => {:delete => :get},
    :collection => {:search => :get} do |contact|
    contact.resource :contact_list, :as => 'listas'
    contact.resource :contact_email, :as => 'correo'
  end
  map.resources :projects, :as => 'proyectos'
  map.resources :proposals, :as => 'propuestas'
  map.resources :shared_lists, :as => 'listas_compartidas' do |shared_list|
    shared_list.resources :shared_list_contacts, :as => 'contactos'
  end
  map.resources :subscriber_lists, :collection => {:search => :get}, :as => 'listas' do |list|
    list.resources :list_subscribers, :as => 'contactos', :collection => {:destroy_all => :delete}
    list.resources :list_shared_lists, :as => 'compartidas'
    list.resource :list_export, :as => 'exportar'
    list.resource :list_import, :as => 'importar', :member => {:preview => :post}
  end

  map.resources :comments
  map.resources :password_resets, :only => [ :new, :create, :edit, :update ], :as => 'recuperar_contrasena'


  # ADMIN
  map.namespace :admin do |admin|
    admin.resources :spaces, :as => 'spaces' do |space|
      space.resources :users, :as => 'usuarios'
      space.resources :space_contacts, :as => 'contactos'
      space.resources :space_subscriber_lists, :as => 'listas'
    end
    admin.resources :jobs, :as => 'tareas', :member => {:execute => :post}
    admin.resources :users, :as => 'usuarios' do |users|
      users.resource :roles, :as => 'roles'
    end

    admin.resources :contacts, :as => 'contactos', :collection => {:search => :get}
    admin.resources :subscriber_lists, :as => 'listas'
    admin.resources :campaigns, :as => 'campanyas' do |campaign|
      campaign.resources :sendings, :as => 'envios'
    end
  end



  # #map.resources :subscriber_lists, :member => { :filter_by_hobbies => :post, :import => :post, :add_all_to => :get, :share => :any, :unshare => :get, :generate_pdf => :get, :generate_excel => :get,
  # :destroy_with_subscribers => :delete} do |subscriber_list|
  #  subscriber_list.resources :contacts, :collection => {:add_by_type_to => :any, :add_to_list => :any}
  # #end

  map.connect "#{ConfirmationsController::ACCEPT_URL}/:id/:code", :controller => 'confirmations', :action => 'accept'
  map.connect "#{ConfirmationsController::REJECT_URL}/:id/:code", :controller => 'confirmations', :action => 'reject'

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
end

#ActionController::Routing::Translator.i18n('es')
#ActionController::Routing::Translator.translate_from_file('config','i18n-routes.yml')

app/models/subscriber_list.rb
class SubscriberList < ActiveRecord::Base
  CONTACTS_PER_PAGE = 30

  after_create :clone_list_if_specified
  default_scope :order => 'id DESC'

  attr_accessor :active

  validates_presence_of :name
  validates_presence_of :space
  validates_uniqueness_of :name, :scope => :space_id


  belongs_to :space
  belongs_to :shares_space, :class_name => 'Space'
  has_many :comments, :as => :commentable, :dependent => :destroy
  belongs_to :user
  
  has_many :subscribers, :dependent => :destroy
  
  has_many :subscriber_contacts, :through => :subscribers, :source => :contact do
    def confirmed
      find(:all, :conditions => {:confirmed => true})
    end
  end
  
  has_many :confirmed, :through => :subscribers, :source => :contact,
    :conditions => {:confirmed => true}
  has_many :active_subscribers, :class_name => 'Subscriber', :conditions => {:active => true}
  has_many :active_contacts, :through => :active_subscribers, :source => :contact

  has_and_belongs_to_many :hobbies
  has_and_belongs_to_many :institution_types

  has_many :shared_lists

  def contacts
    auto_update? ? filter.contacts : subscriber_contacts
  end

  def confirmed_contacts
    auto_update? ? filter.confirmed_contacts : subscriber_contacts.confirmed
  end

  def contacts_count
    auto_update? ? filter.length : subscribers.length
  end

  def confirmed_contacts_count
    auto_update? ? filter.confirmed_length : subscriber_contacts.confirmed.length
  end

  def filter
    @filter ||= ContactFilter.new(self)
  end


  def clone_list_id
    @clone_list_id
  end

  def clone_list_id=(id)
    @clone_list_id = id
  end

  def has_finder?
    self.hobbies.present? || self.contact_type_id.present?
  end

  def before_save
    self.contact_subtype_id = nil if self.contact_type_id != 2
  end

  def already_set?
    self.all_general.present? || self.all_institutions.present? || self.all_comunication.present? || self.all_artists.present? || self.hobbies.present? || self.institution_types.present?
  end

  def info
    contacts = auto_update? ? 'lista inteligente' : "#{self.contacts_count} contactos"
    "#{self.space.name} - #{self.name} (#{contacts})"
  end

  protected
  def clone_list_if_specified
    if @clone_list_id.present?
      puts "CLONE! #{@clone_list_id}"
      other = SubscriberList.find @clone_list_id
      self.contacts << other.contacts
      self.save!
    end
  end
end

app/controllers/admin/subscriber_lists_controller.rb
class Admin::SubscriberListsController < Admin::AdminController
  before_filter :require_user, :require_admin

  def index
    @lists = SubscriberList.all(:order => 'id DESC')
  end
end

app/controllers/subscriber_lists_controller.rb
class SubscriberListsController < InheritedResources::Base
  before_filter :require_user

  def index
    @search_path = search_subscriber_lists_path
    index!
  end

  def new
    params[:auto_update] ||= false
    params[:subscriber_list] ||= {}
    params[:subscriber_list][:auto_update] = params[:auto_update]
    params[:subscriber_list][:user_id] = current_user.id
    @subscriber_list = current_space.subscriber_lists.build(params[:subscriber_list])
    if params[:clone]
      @source_list = current_space.subscriber_lists.find params[:clone]
      @subscriber_list.clone_list_id = params[:clone]
    end
    new!
  end

  def create
    params[:subscriber_list][:auto_update] ||= false
    create!
  end

  def search
    @subscriber_lists = current_space.subscriber_lists.find(:all, :conditions =>
        "name LIKE '%#{params[:query]}%'", :limit => 30)
  end

  protected
  def begin_of_association_chain
    current_space
  end
end

app/views/subscriber_lists/_filter.html.haml
%table
  %tr
    %td{ :valign => :top }
      = f.check_box :all_general
      Todos los usuarios
      %br/
      - for hobbies in Hobby.find(:all, :conditions => ["name != 'otros'"]).in_groups_of(3, false)
        %div{:style => 'float:left; margin-right: 80px'}
          - for hobby in hobbies
            = check_box_tag "subscriber_list[hobby_ids][]", hobby.id, @subscriber_list.hobbies.include?(hobby), :class => 'hobby_checkbox'
            = hobby.name
            %br/


%table
  %tr
    %td
      Añadir Instituciones
%table
  %tr
    %td{ :valign => :top }
      = f.check_box :all_institutions
      Todas las instituciones
      %br/
      - for institution_types in InstitutionType.all.in_groups_of(6, false)
        %div{:style => 'float:left; margin-right: 80px'}
          - for institution_type in institution_types
            = check_box_tag "subscriber_list[institution_type_ids][]", institution_type.id, @subscriber_list.institution_types.include?(institution_type), :class => 'institution_type_checkbox'
            = institution_type.name
            %br/

%table
  %tr
    %td
      Añadir medios de comunicación
  %tr
    %td{ :valign => :top }
      = f.check_box :all_comunication
      Todos los contactos
%table
  %tr
    %td
      Añadir Artistas - Profesionales
  %tr
    %td{ :valign => :top }
      = f.check_box :all_artists
      Todos los contactos

app/views/subscriber_lists/_form.html.haml
= f.error_messages
= f.hidden_field :user_id
= f.hidden_field :auto_update
%table(width="500" cellpadding="0" cellspacing="0")
  - if !@subscriber_list.new_record?
    %tr
      %td(valign="top")
        .label.top.req= "Tipo:"
        = @subscriber_list.auto_update? ? 'Lista inteligente' : 'Lista normal'
  %tr
    %td(valign="top")
      .label.top.req= "Nombre:"
      = f.text_field :name
  %tr
    %td(valign="top")
      .label.top.req= "Descripción:"
      = f.text_area :description, :rows => 5

- if @subscriber_list.new_record? && !@subscriber_list.auto_update?
  %table
    %tr
      %td(valign="top")
        %br/
        - if @source_list
          %b= "Se copiarán todos los contactos (#{@source_list.contacts_count}) de la lista '#{@source_list.name}'"
          = f.hidden_field :clone_list_id
        - else
          .label.top.req= "Copiar contactos de la lista:"
          Todos los contactos de la lista seleccionada se copiarán a la nueva lista.<br/>
          Deja este campo en blanco para crear una lista vacía.
          %br/
          = f.collection_select :clone_list_id, current_space.subscriber_lists(:include => :space), :id, :info, {:selected => params[:clone].to_i, :include_blank => params[:clone].blank?}



- if @subscriber_list.auto_update?
  %table
    %tr
      %td(valign="top")
        .label.top.req= "Criterios de la lista inteligente:"
        Selecciona los criterios que deben cumplir los contactos para estar en esta lista.
  = render :partial => 'filter', :locals => {:f => f}

<br/><br/>

app/views/subscriber_lists/_subscriber_list.html.haml
%li
  .tools
    = link_to("Ver contactos", subscriber_list_list_subscribers_path(subscriber_list)) + " | "
    - if can? :manage, subscriber_list
      = link_to("Gestionar", subscriber_list_path(subscriber_list))
      |
      = link_to("Editar", edit_subscriber_list_path(subscriber_list))
      |
      = link_to "Guardar como...", new_subscriber_list_path(:clone => subscriber_list.id)
      |
      = link_to 'Borrar', subscriber_list_path(subscriber_list), :method => :delete,
       :confirm => "Vas a borrar la lista #{subscriber_list.name}. ¡¿Estás seguro?!"

  .indentslim
    = link_to h(subscriber_list.name), subscriber_list_path(subscriber_list)
    %tt
      = " &ndash; "
      = t(:added_by, :time_ago => time_ago_in_words(subscriber_list.created_at), :user => (subscriber_list.user_id == current_user.id ? t(:me) : h(subscriber_list.user.try(:full_name))))
      = ", espacio <b>#{subscriber_list.space.name}</b>" if current_user.is_superadmin?
    %dt
      - if subscriber_list.auto_update?
        = "<b>Lista inteligente</b>"
      - else
        = pluralize(subscriber_list.contacts.length, "contacto", "contactos")
        = "(#{pluralize(subscriber_list.confirmed.length, "confirmado", "confirmados")})"
    - if (shared_lists = subscriber_list.shared_lists).present?
      %dt
        Compartida con:
        - shared_lists.each_with_index do |sl, index|
          = ", " if index != 0
          %b= sl.space.name
 

app/views/subscriber_lists/edit.html.haml
.title
  %span 
    = "Editar lista de envío '#{@subscriber_list.name}'"

- form_for @subscriber_list do |f|
  .remote
    .section
    = render :partial => "form", :locals => {:f => f}

  .buttonbar
    = f.submit((@subscriber_list.new_record? ? 'Crear lista' : 'Guardar lista'), :class => 'btn')
    = link_to('Cancelar', (@subscriber_list.new_record? ? subscriber_lists_path : subscriber_list_path(@subscriber_list)))

app/views/subscriber_lists/index.html.haml
.title_tools
  - if current_user.is_subscriber_lists_manager?
    = link_to("Crear lista", new_subscriber_list_path)
    |
    = link_to("Crear lista inteligente", new_subscriber_list_path(:auto_update => true))

.title
  %span= title "Listas de envío (#{@subscriber_lists.size}) - Espacio '#{current_space.name}'"

.list.search#subscriber_lists
  - unless @subscriber_lists.empty?
    = render :partial => "subscriber_list", :collection => @subscriber_lists
  - else
    = render :partial => "common/empty"

  %br/
  .title
    %span= "Listas de envío compartidas con '#{current_space.name}' (#{current_space.shared_lists.size})"
  .list#contacts
    - if current_space.shared_lists.present?
      = render :partial => "shared_lists/shared_list", :collection => current_space.shared_lists
    - else
      Ninguna.

app/views/subscriber_lists/new.html.haml
.title
  - if @source_list
    %span=  "Guardar lista de envío '#{@source_list.name}' con otro nombre"
  - else
    %span=  "Crear lista de envío #{@subscriber_list.auto_update? ? 'inteligente' : 'normal'}"

- if @subscriber_list.auto_update?
  %h2 Una lista inteligente actualiza automáticamente cuando se añaden nuevos contactos con los mismos criterios que los de la lista.

- form_for @subscriber_list do |f|
  .remote
    .section
    = render :partial => "form", :locals => {:f => f}

  .buttonbar
    = f.submit((@subscriber_list.new_record? ? 'Crear lista' : 'Guardar lista'), :class => 'btn')
    = link_to('Cancelar', (@subscriber_list.new_record? ? subscriber_lists_path : subscriber_list_path(@subscriber_list)))

app/views/subscriber_lists/old.form.html.haml
- form_for @subscriber_list do |f|
  = f.error_messages
  = f.hidden_field :user_id, :value => @subscriber_list.user_id || current_user.id
  .remote
    .section
      %table(width="500" cellpadding="0" cellspacing="0")
        - if !@subscriber_list.new_record?
          %tr
            %td(valign="top")
              .label.top.req= "Tipo:"
              = @subscriber_list.auto_update? ? 'Lista inteligente' : 'Lista normal'
        %tr
          %td(valign="top")
            .label.top.req= "Nombre:"
            = f.text_field :name
        %tr
          %td(valign="top")
            .label.top.req= "Descripción:"
            = f.text_area :description, :rows => 5

        - if @subscriber_list.new_record?
          %tr
            %td.form_section(valign="top")
              = f.radio_button :auto_update, false
              %label Lista normal
          %tr
            %td(valign="top")
              .label.top.req= "Copiar contactos de la lista:"
              = f.collection_select :clone_list_id, current_space.subscriber_lists, :id, :info, {:selected => params[:clone].to_i, :include_blank => params[:clone].blank?}

      - if params[:clone].blank?
        %table
          - if @subscriber_list.new_record?
            %tr
              %td.form_section
                = f.radio_button :auto_update, true
                %label Lista inteligente
          - if @subscriber_list.new_record? || @subscriber_list.auto_update?
            %tr
              %td
                .label.top.req= "Contactos de la lista inteligente:"
            %tr
              %td
                Añadir usuarios generales

          %table
            %tr
              %td{ :valign => :top }
                = f.check_box :all_general
                Todos los usuarios
                %br/
                - for hobbies in Hobby.find(:all, :conditions => ["name != 'otros'"]).in_groups_of(3, false)
                  %div{:style => 'float:left; margin-right: 80px'}
                    - for hobby in hobbies
                      = check_box_tag "subscriber_list[hobby_ids][]", hobby.id, @subscriber_list.hobbies.include?(hobby), :class => 'hobby_checkbox'
                      = hobby.name
                      %br/

          %table
            %tr
              %td
                Añadir Instituciones
          %table
            %tr
              %td{ :valign => :top }
                = f.check_box :all_institutions
                Todas las instituciones
                %br/
                - for institution_types in InstitutionType.all.in_groups_of(6, false)
                  %div{:style => 'float:left; margin-right: 80px'}
                    - for institution_type in institution_types
                      = check_box_tag "subscriber_list[institution_type_ids][]", institution_type.id, @subscriber_list.institution_types.include?(institution_type), :class => 'institution_type_checkbox'
                      = institution_type.name
                      %br/

          %table
            %tr
              %td
                Añadir medios de comunicación
            %tr
              %td{ :valign => :top }
                = f.check_box :all_comunication
                Todos los contactos
          %table
            %tr
              %td
                Añadir Artistas - Profesionales
            %tr
              %td{ :valign => :top }
                = f.check_box :all_artists
                Todos los contactos

      .buttonbar
        = f.submit((@subscriber_list.new_record? ? 'Crear lista' : 'Guardar lista'), :class => 'btn')
        = link_to('Cancelar', (@subscriber_list.new_record? ? subscriber_lists_path : subscriber_list_path(@subscriber_list)))

app/views/subscriber_lists/search.js.erb
<% if @subscriber_lists.present? %>
  $(".search").html("<%= escape_javascript render(:partial => 'subscriber_list', :collection => @subscriber_lists) %>");
  <% if @subscriber_lists.size == 30 %>
    $(".search").append("<b>La búsqueda se ha limitado a 30 elementos.</b>");
  <% end %>
<% else %>
  $(".search").html("<%= escape_javascript render(:partial => 'common/empty_search') %>");
<% end %>

app/views/subscriber_lists/show.html.haml
.title_tools#menu
  %span#subscribers_count= pluralize(@subscriber_list.contacts_count, 'contacto', 'contactos')
  - if can? :manage, @subscriber_list
    |
    = link_to("Volver", subscriber_lists_path)
    =# link_to("Eliminar", @subscriber_list, :method => :delete, :confirm => '¿Estás seguro que quieres eliminar la lista?')

.title
  %span
    = title "Lista '#{@subscriber_list.name}' - Espacio '#{@subscriber_list.space.name}' (#{@subscriber_list.contacts_count})"
    = "(Compartida, sólo lectura)" unless current_space.id == @subscriber_list.space_id

%div.actions
  %p
    Gestionar lista:
    = link_to 'Editar', edit_subscriber_list_path(resource)
    |
    = link_to 'Guardar como...', new_subscriber_list_path(:clone => @subscriber_list.id)
    |
    = link_to 'Borrar la lista (pero no sus contactos)', subscriber_list_path(@subscriber_list), :method => :delete, :confirm => "Vas a borrar esta lista. ¡¿Estás segurx?!"
  %p
    Gestionar contactos:
    = link_to 'Ver', subscriber_list_list_subscribers_path(resource)
    - if can? :manage, @subscriber_list
      |
      = link_to 'Borrar', subscriber_list_list_subscribers_path(resource, :borrar => 'si')
      |
      = link_to 'Borrar todos los contactos de esta lista', destroy_all_subscriber_list_list_subscribers_path(resource),
        :method => :delete, :confirm => "CUIDADO!!! ESTÁS A PUNTO DE BORRAR TODOS LOS CONTACTOS DE ESTA LISTA. ESTA ACCIÓN NO SE PUEDE DESHACER. ¿ESTÁS SEGURO?"
  %p
    Compartir lista:
    = link_to 'Compartir', new_shared_list_path(:list => @subscriber_list.id)
  %p
    Añadir contactos:
    = link_to 'De otra lista', new_subscriber_list_list_import_path(@subscriber_list, :source => 'list')
    |
    = link_to 'Buscando', new_subscriber_list_list_import_path(@subscriber_list, :source => 'search')
    |
    = link_to 'Usando un filtro', new_subscriber_list_list_import_path(@subscriber_list, :source => 'filter')
    |
    = link_to 'Desde un archivo de excel', new_subscriber_list_list_import_path(@subscriber_list, :source => 'excel')
  %p
    Exportar contactos:
    -#= link_to 'En PDF', subscriber_list_list_export_path(@subscriber_list, :format => 'pdf')
    -#|
    = link_to 'En Excel', subscriber_list_list_export_path(@subscriber_list, :format => 'xls')

%h2 Información general
%p.properties
  %label= "Tipo: #{@subscriber_list.auto_update? ? 'Lista inteligente' : 'Lista normal'}<br/>"
  %label= "Nombre: #{@subscriber_list.name}<br/>"
  %label= "Descripción: #{@subscriber_list.description}<br/>"
  %label= "Espacio: #{@subscriber_list.space.name} (#{@subscriber_list.space_id == current_space.id ? 'Lista propia' : 'Lista compartida'})<br/>"
  %label= "Número contactos: #{@subscriber_list.contacts_count}<br/>"
  %label= "Número de contactos confirmados: #{@subscriber_list.confirmed_contacts_count}"

%h2 Compartir
%ul.list
  - @subscriber_list.shared_lists.each do |shared|
    %li
      .indentslim
        = "Compartida con espacio '#{shared.space.name}'"
        = link_to "(Dejar de compartir)",  shared, :method => :delete,
          :confirm => "¿Quiere dejar de compartir la lista #{shared.subscriber_list.name} con #{shared.space.name}?"
  - if @subscriber_list.shared_lists.size == 0
    %li
      .indentslim= 'No está compartida con ningún espacio'